### ISSUE TITLE
The problem of test code and PSNR in Grayscale dataset

### ISSUE THREAD

**Issue by lan122942983** [akshaydudhane16/BIPNet#10]
Dear akshaydudhane16,

First of all, thanks for your reply. I understand there is a part of Grayscale_denoising_testing.py that calculates PSNR. However, the psnr calculated is before DenoisingPostProcess, while the psnr calculated is after DenoisingPostProcess in other methods, like MFIR, BPN. 

Through the evaluation method of BPN, MFIR, I can actually only get the psnr(38.83, 36.07, 33.05, 29.44, 34.35), which is different from the psnr(41.26, 38.74, 35.91, 31.35, 36.81) in your paper. For fair, BPN, MFIR, BIPNET are all about getting the image and then evaluating it. 

So I have a little bit of a problem with that, I'm looking forward to your answers.

Thanks,

**Comment by akshaydudhane16** [comment]
Results of the proposed BIPNet with post-processing (on sRGB) are available now. Please consider the updated PSNR values for comparison.
