### ISSUE TITLE
Loss nan for BurstSR Track 2 training 

### ISSUE THREAD

**Issue by bluedream1121** [akshaydudhane16/BIPNet#14]
When I train the real-world burst SR benchmark using Track_2_evaluation.py, the value of loss becomes nan.

I did not modify any of the source code from the released version.

<img width="1101" alt="loss_nan_track2_bipnet" src="https://user-images.githubusercontent.com/15090092/218739927-01f033fa-73eb-418b-818a-eafc6e8a563d.png">

Do you know how to fix this issue?

**Comment by bluedream1121** [comment]
this is an issue of the evaluation metric.

**Comment by SuperStacie** [comment]
Hi, I met the same problem, how do you solve it? Thanks!
