### ISSUE TITLE
The Results on Track2 of Burst SR Cannot be Reproduced

### ISSUE THREAD

**Issue by greatlog** [akshaydudhane16/BIPNet#16]
Hi, I used the provided checkpoint for real burst SR and run Track_2_evaluation.py. The reproduced result is much lower than the reported one in your paper.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/24616259/232961173-5ee55356-2a58-4a8b-8e75-687425591787.png">

As shown in the figure, the reproduced PSNR is 47.42, while the reported PSNR in the paper is 48.63. Is there any problem?

Thanks.

**Comment by akshaydudhane16** [comment]
Use updated Track_2_evaluation.py file to evaluate the BIPNet for BurstSR dataset.
