### ISSUE TITLE
The pre-trained model gets no paper points

### ISSUE THREAD

**Issue by lan122942983** [akshaydudhane16/BIPNet#7]
Sorry to bother you, but I have a question. I have tried to use the MFIR test code to evalute the psnr of BIPNET about grayscale denoising. However, I can only get 38.79 dB with gain 1 different from 41.26 dB in your paper. So I want to know what the problem is? Thanks, looking forward to your reply.

**Comment by akshaydudhane16** [comment]
We have collected and reported results using our framework. Please run the Grayscale_denoising_testing.py file to get the results for the Grayscale dataset.
