### ISSUE TITLE
The results in Grayscale dataset are 3dB less than the PSNR in paper

### ISSUE THREAD

**Issue by lan122942983** [akshaydudhane16/BIPNet#9]
Dear akshaydudhane16,

        I'm so sorry to bother you with a question. Through the MFIR evaluation code, I got the test results of your pretrained model on the grayscale dataset, which is very different from the results(41.26, 38.74, 35.91, 31.35, 36.81) in your paper. I would be most grateful if you could reply to me. 
                                                                                                                        
Thanks,

<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

1 | 2 | 4 | 8 | average
-- | -- | -- | -- | --
38.83 | 36.07 | 33.05 | 29.44 | 34.35

</body>

</html>

**Comment by akshaydudhane16** [comment]
I have collected and reported all the results through our framework. Please run the Grayscale_denoising_testing.py file to get the results for the Grayscale dataset.

**Comment by lan122942983** [comment]
Dear akshaydudhane16,
First of all, thanks for your reply. I understand there is a part of Grayscale_denoising_testing.py that calculates PSNR. However,  the psnr calculated is before DenoisingPostProcess, while the psnr calculated is after DenoisingPostProcess in other methods, like MFIR, BPN. So I have a little bit of a problem with that, I'm looking forward to your answers. 
Thanks,
